export const MockData = [
  {
    id: 1,
    name: "Frog Star #8798",
    image: "/Image_fx-292 1.png",
    price: "7978",
    collection: "CryptoPunks",
  },
  {
    id: 2,
    name: "Frog Star #8798",
    image: "/Image_fx-293 1.png",
    price: "7978",
    collection: "Bored Apes",
  },
  {
    id: 3,
    name: "Frog Star #8798",
    image: "/Image_fx-297 1.png",
    price: "7978",
    collection: "Art Blocks",
  },
  {
    id: 4,
    name: "Frog Star #8798",
    image: "/Image_fx-296 1.png",
    price: "7978",
    collection: "Doodles",
  },
  {
    id: 5,
    name: "Frog Star #8798",
    image: "/Image_fx-299 1.png",
    price: "7978",
    collection: "CloneX",
  },
  {
    id: 6,
    name: "Frog Star #8798",
    image: "/Image_fx-300 1.png",
    price: "7978",
    collection: "Azuki",
  },
  {
    id: 7,
    name: "Frog Star #8798",
    image: "/Image_fx-294 1.png",
    price: "7978",
    collection: "Moonbirds",
  },
  {
    id: 8,
    name: "Frog Star #8798",
    image: "/Image_fx-301 1.png",
    price: "7978",
    collection: "Meebits",
  },
  {
    id: 9,
    name: "Frog Star #8798",
    image: "/Image_fx-302 1.png",
    price: "7978",
    collection: "World of Women",
  },
  {
    id: 10,
    name: "Frog Star #8798",
    image: "/Image_fx-303 1.png",
    price: "7978",
    collection: "Miladys",
  },
];
